import type { Service, Booking, TimeSlot, Testimonial, Category } from '@/types';
import serviceHeadSpa from '@/assets/service-head-spa.jpg';
import serviceAromatherapy from '@/assets/service-aromatherapy.jpg';
import servicePremium from '@/assets/service-premium.jpg';
import serviceDeluxe from '@/assets/service-deluxe.jpg';
import serviceHotStone from '@/assets/service-hot-stone.jpg';
import serviceScalpDetox from '@/assets/service-scalp-detox.jpg';
import serviceNeckShoulder from '@/assets/service-neck-shoulder.jpg';
import serviceHerbalSteam from '@/assets/service-herbal-steam.jpg';
import serviceDeepTissue from '@/assets/service-deep-tissue.jpg';

// Gallery images
import gallery1 from '@/assets/gallery-1.jpg';
import gallery2 from '@/assets/gallery-2.jpg';
import gallery3 from '@/assets/gallery-3.jpg';
import gallery4 from '@/assets/gallery-4.jpg';
import gallery5 from '@/assets/gallery-5.jpg';
import gallery6 from '@/assets/gallery-6.jpg';
import gallery7 from '@/assets/gallery-7.jpg';
import gallery8 from '@/assets/gallery-8.jpg';
import gallery9 from '@/assets/gallery-9.jpg';

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Massage Rituals',
    slug: 'massage-rituals',
    seoTitle: 'Massage Rituals | Relaxing Massage Treatments',
    metaKeywords: 'massage spa, aromatherapy massage, shiatsu massage, hot stone massage',
    metaDescription: 'Explore relaxing massage rituals including aromatherapy bliss, shiatsu therapy, and luxury spa combos.',
    parentId: null,
    sort: 1,
    status: true,
  },
  {
    id: 2,
    name: 'Head Spa Rituals',
    slug: 'japanese-head-spa-rituals',
    seoTitle: 'Japanese Head Spa Treatments',
    metaKeywords: 'japanese head spa, scalp spa treatment, head massage spa',
    metaDescription: 'Traditional Japanese head spa rituals designed for deep relaxation, scalp cleansing, and rejuvenation.',
    parentId: null,
    sort: 2,
    status: true,
  },
];

export const mockServices: Service[] = [
  // ── Category 1: Massage Rituals ──
  {
    id: '1',
    categoryId: 1,
    name: 'Aromatherapy Bliss',
    slug: 'aromatherapy-bliss-massage',
    price: 100,
    duration: 60,
    description: 'Inspired by traditional Swedish massage, this aromatherapy treatment melts away tension and restores deep harmony. Using carefully selected essential oils, each session is tailored to your mood and needs, promoting complete relaxation of mind and body.',
    shortDescription: 'Relaxing Swedish-inspired aromatherapy massage.',
    image: serviceAromatherapy,
    features: ['Personalized oil blend', 'Stress relief massage', 'Scalp treatment', 'Aromatherapy inhalation', 'Hot towel wrap'],
    hot: false,
    status: true,
    seoTitle: 'Aromatherapy Bliss Massage | Relaxing Swedish Spa Treatment',
    metaKeywords: 'aromatherapy massage, swedish massage spa, relaxation massage',
    metaDescription: 'Enjoy a relaxing aromatherapy bliss massage inspired by Swedish techniques to melt away tension and restore harmony.',
    packages: [{ serviceId: 1, durationMinutes: 60, price: 100 }],
  },
  {
    id: '2',
    categoryId: 1,
    name: 'Remedial Shiatsu / Cupping / Hot Stone',
    slug: 'shiatsu-cupping-hot-stone-massage',
    price: 150,
    duration: 90,
    description: 'A therapeutic massage using finger pressure, stretching, and gentle techniques to release tension, improve circulation, and promote deep relaxation. Choose from Shiatsu, cupping, or hot stone therapy — or combine them for a personalised healing experience.',
    shortDescription: 'Traditional Japanese Shiatsu therapy for body balance.',
    image: serviceHotStone,
    features: ['Shiatsu pressure therapy', 'Cupping option', 'Hot stone placement', 'Improved circulation', 'Deep tension relief'],
    hot: false,
    status: true,
    seoTitle: 'Shiatsu, Cupping & Hot Stone Massage',
    metaKeywords: 'shiatsu massage, hot stone massage, cupping therapy massage',
    metaDescription: 'Experience therapeutic Shiatsu massage combined with cupping or hot stone treatment to relieve tension and restore balance.',
    packages: [{ serviceId: 2, durationMinutes: 90, price: 150 }],
  },
  {
    id: '3',
    categoryId: 1,
    name: 'Luxury Spa Combo: Head Spa + Massage',
    slug: 'luxury-spa-combo-head-spa-massage',
    price: 235,
    duration: 150,
    description: 'The ultimate spa experience combining our signature Japanese head spa with a full body massage. Begin with a deep scalp treatment and finish with an aromatherapy or Shiatsu body massage — a complete head-to-toe rejuvenation ritual.',
    shortDescription: 'Complete head spa plus full body massage combo.',
    image: serviceDeluxe,
    features: ['Full head spa treatment', 'Body massage included', 'Aromatherapy oils', 'Scalp conditioning', 'Premium tea service'],
    hot: true,
    status: true,
    seoTitle: 'Luxury Spa Combo | Head Spa + Body Massage Package',
    metaKeywords: 'spa combo, head spa massage, luxury spa package, full body massage',
    metaDescription: 'Indulge in the luxury spa combo with Japanese head spa and full body massage for ultimate rejuvenation.',
    packages: [{ serviceId: 3, durationMinutes: 150, price: 235 }],
  },
  {
    id: '4',
    categoryId: 1,
    name: 'Deep Tissue Relaxation',
    slug: 'deep-tissue-relaxation-massage',
    price: 180,
    duration: 120,
    description: 'A full-body deep tissue massage that targets chronic muscle tension and promotes complete relaxation. Using firm pressure and slow strokes, this treatment works on the deeper layers of muscle and connective tissue, providing both physical relief and mental tranquility.',
    shortDescription: 'Full-body deep tissue massage for chronic tension relief.',
    image: serviceDeepTissue,
    features: ['Full body massage', 'Deep tissue techniques', 'Aromatherapy oils', 'Chronic tension relief', 'Mental relaxation'],
    hot: false,
    status: true,
    seoTitle: 'Deep Tissue Relaxation Massage | Full Body Therapy',
    metaKeywords: 'deep tissue massage, full body massage, tension relief massage',
    metaDescription: 'Full-body deep tissue massage targeting chronic tension with aromatherapy for complete relaxation and mental tranquility.',
    packages: [{ serviceId: 4, durationMinutes: 120, price: 180 }],
  },
  // ── Category 2: Head Spa Rituals ──
  {
    id: '5',
    categoryId: 2,
    name: 'Traditional Japanese Head Spa',
    slug: 'traditional-japanese-head-spa',
    price: 100,
    duration: 70,
    description: 'Experience the authentic Japanese head spa treatment perfected over centuries. This deeply relaxing ritual focuses on your scalp, neck, and shoulders using traditional techniques combined with premium botanical products. Your session begins with scalp analysis, followed by a customised cleansing ritual, deep conditioning, and an extended head and neck massage.',
    shortDescription: 'Authentic Japanese head spa focusing on scalp and relaxation.',
    image: serviceHeadSpa,
    features: ['Scalp analysis', 'Deep cleansing ritual', 'Botanical conditioning', 'Extended head massage', 'Neck & shoulder massage'],
    hot: false,
    status: true,
    seoTitle: 'Traditional Japanese Head Spa | Authentic Scalp Treatment',
    metaKeywords: 'japanese head spa, scalp treatment, head massage, traditional spa',
    metaDescription: 'Experience the authentic traditional Japanese head spa treatment for deep scalp relaxation and rejuvenation.',
    packages: [{ serviceId: 5, durationMinutes: 70, price: 100 }],
  },
  {
    id: '6',
    categoryId: 2,
    name: 'Premium Japanese Head Spa',
    slug: 'premium-japanese-head-spa',
    price: 135,
    duration: 90,
    description: 'Our premium offering takes the traditional head spa experience to new heights. This extended session includes everything in our traditional treatment plus additional luxury elements such as a hot stone facial massage, premium Japanese hair treatment, and an extended relaxation period with our exclusive range of imported Japanese botanical products.',
    shortDescription: 'Extended luxury head spa with premium Japanese products.',
    image: servicePremium,
    features: ['Everything in Traditional', 'Hot stone facial massage', 'Premium Japanese products', 'Extended relaxation', 'Complimentary tea ceremony'],
    hot: true,
    status: true,
    seoTitle: 'Premium Japanese Head Spa | Luxury Scalp & Hair Treatment',
    metaKeywords: 'premium head spa, luxury head spa, japanese scalp treatment, premium spa',
    metaDescription: 'Enjoy an elevated premium Japanese head spa experience with luxury additions and imported botanical products.',
    packages: [{ serviceId: 6, durationMinutes: 90, price: 135 }],
  },
  {
    id: '7',
    categoryId: 2,
    name: 'Scalp Detox & Renewal',
    slug: 'scalp-detox-renewal',
    price: 135,
    duration: 90,
    description: 'A targeted scalp treatment designed to deeply cleanse, detoxify, and revitalise your scalp. Using premium Japanese botanical products, this treatment removes product build-up, excess oil, and impurities while nourishing the scalp with vitamins and minerals. Ideal for those experiencing scalp concerns or seeking healthier, more vibrant hair.',
    shortDescription: 'Deep detox scalp treatment with Japanese botanicals.',
    image: serviceScalpDetox,
    features: ['Deep scalp cleanse', 'Detoxifying treatment', 'Japanese botanical products', 'Scalp nourishment', 'Stimulating massage'],
    hot: false,
    status: true,
    seoTitle: 'Scalp Detox & Renewal Treatment | Deep Cleanse Spa',
    metaKeywords: 'scalp detox, scalp treatment, deep cleanse spa, head spa detox',
    metaDescription: 'Deep cleansing scalp treatment to detoxify, remove build-up, and revitalise with Japanese botanicals.',
    packages: [{ serviceId: 7, durationMinutes: 90, price: 135 }],
  },
  {
    id: '8',
    categoryId: 2,
    name: 'Herbal Steam Head Spa',
    slug: 'herbal-steam-head-spa',
    price: 110,
    duration: 70,
    description: 'A luxurious head spa treatment combining the benefits of herbal steam with Japanese scalp care rituals. Warm herbal steam opens pores and prepares the scalp for deep cleansing, followed by a customised scalp massage and nourishing mask. This treatment leaves your scalp refreshed and your hair rejuvenated with a healthy shine.',
    shortDescription: 'Herbal steam head spa for scalp cleansing and shine.',
    image: serviceHerbalSteam,
    features: ['Herbal steam therapy', 'Deep pore cleansing', 'Japanese scalp ritual', 'Scalp massage', 'Nourishing hair mask'],
    hot: false,
    status: true,
    seoTitle: 'Herbal Steam Head Spa | Scalp Cleansing Treatment',
    metaKeywords: 'herbal steam spa, head spa steam, scalp cleansing, herbal treatment',
    metaDescription: 'Luxurious herbal steam head spa combining steam therapy with Japanese scalp care for refreshed, shiny hair.',
    packages: [{ serviceId: 8, durationMinutes: 70, price: 110 }],
  },
  {
    id: '9',
    categoryId: 2,
    name: 'Neck & Shoulder Relief + Head Spa',
    slug: 'neck-shoulder-relief-head-spa',
    price: 140,
    duration: 90,
    description: 'Focused relief for the neck, shoulders, and upper back combined with a revitalising Japanese head spa treatment. This combination uses deep tissue techniques, acupressure, and stretching to release knots and reduce pain, followed by a complete scalp treatment for total relaxation from head to shoulders.',
    shortDescription: 'Neck & shoulder relief combined with head spa treatment.',
    image: serviceNeckShoulder,
    features: ['Deep tissue techniques', 'Acupressure points', 'Tension release', 'Full scalp treatment', 'Posture improvement'],
    hot: false,
    status: true,
    seoTitle: 'Neck & Shoulder Relief + Head Spa | Tension Release Treatment',
    metaKeywords: 'neck shoulder massage, head spa combo, tension relief, upper body massage',
    metaDescription: 'Targeted neck and shoulder relief with Japanese head spa for complete upper body relaxation and tension release.',
    packages: [{ serviceId: 9, durationMinutes: 90, price: 140 }],
  },
];

export const mockGalleryImages = [
  { src: gallery1, alt: 'Japanese zen spa interior' },
  { src: gallery2, alt: 'Spa treatment room' },
  { src: gallery3, alt: 'Relaxation area' },
  { src: serviceHeadSpa, alt: 'Head spa treatment' },
  { src: serviceAromatherapy, alt: 'Aromatherapy session' },
  { src: servicePremium, alt: 'Premium spa experience' },
  { src: gallery4, alt: 'Zen garden with raked sand' },
  { src: gallery5, alt: 'Premium Japanese spa products' },
  { src: gallery6, alt: 'Tea ceremony at the spa' },
  { src: gallery7, alt: 'Spa lounge and waiting area' },
  { src: gallery8, alt: 'Aromatherapy oil diffuser' },
  { src: gallery9, alt: 'Treatment bed with flower petals' },
  { src: serviceHotStone, alt: 'Hot stone therapy session' },
  { src: serviceNeckShoulder, alt: 'Relaxation treatment' },
  { src: serviceDeepTissue, alt: 'Deep tissue massage atmosphere' },
];

export const mockTimeSlots: TimeSlot[] = [
  { id: '1', time: '09:00', available: true },
  { id: '2', time: '09:30', available: true },
  { id: '3', time: '10:00', available: false },
  { id: '4', time: '10:30', available: true },
  { id: '5', time: '11:00', available: true },
  { id: '6', time: '11:30', available: false },
  { id: '7', time: '12:00', available: true },
  { id: '8', time: '12:30', available: true },
  { id: '9', time: '13:00', available: false },
  { id: '10', time: '13:30', available: true },
  { id: '11', time: '14:00', available: true },
  { id: '12', time: '14:30', available: true },
  { id: '13', time: '15:00', available: false },
  { id: '14', time: '15:30', available: true },
  { id: '15', time: '16:00', available: true },
  { id: '16', time: '16:30', available: true },
  { id: '17', time: '17:00', available: true },
  { id: '18', time: '17:30', available: false },
];

export const mockBookings: Booking[] = [
  {
    id: 'b1',
    serviceId: '5',
    serviceName: 'Traditional Japanese Head Spa',
    date: '2026-03-20',
    time: '10:30',
    status: 'confirmed',
    paymentMethod: 'online',
    totalPrice: 100,
    depositAmount: 15,
    createdAt: '2026-03-10T10:00:00Z',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    customerPhone: '0412345678',
  },
  {
    id: 'b2',
    serviceId: '6',
    serviceName: 'Premium Japanese Head Spa',
    date: '2026-03-25',
    time: '14:00',
    status: 'pending_payment',
    paymentMethod: 'at_store',
    totalPrice: 135,
    depositAmount: 0,
    createdAt: '2026-03-11T14:00:00Z',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    customerPhone: '0412345678',
  },
  {
    id: 'b3',
    serviceId: '1',
    serviceName: 'Aromatherapy Bliss',
    date: '2026-02-15',
    time: '11:00',
    status: 'completed',
    paymentMethod: 'online',
    totalPrice: 100,
    depositAmount: 15,
    createdAt: '2026-02-10T09:00:00Z',
    customerName: 'Jane Smith',
    customerEmail: 'jane@example.com',
    customerPhone: '0412345678',
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah M.',
    rating: 5,
    text: 'Absolutely heavenly experience! The head spa treatment was unlike anything I\'ve ever had. I left feeling completely refreshed and my hair has never looked better.',
    date: '2026-02-28',
  },
  {
    id: 't2',
    name: 'Emily T.',
    rating: 5,
    text: 'The Premium Japanese Head Spa was worth every penny. The attention to detail and the serene atmosphere made it a truly transformative experience.',
    date: '2026-02-15',
  },
  {
    id: 't3',
    name: 'Michael R.',
    rating: 5,
    text: 'I came in stressed and left feeling like a new person. The aromatherapy bliss treatment is now my monthly self-care ritual. Highly recommend!',
    date: '2026-01-30',
  },
];
